# Generated by Django 5.1.15 on 2026-09-09 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('planned_duration_mins', models.IntegerField(default=25)),
                ('actual_duration_mins', models.IntegerField(blank=True, null=True)),
                ('interruptions', models.IntegerField(default=0)),
                ('session_type', models.CharField(choices=[('DEEP_WORK', 'Deep Work'), ('POMODORO', 'Pomodoro'), ('STUDY', 'Study'), ('MEETING', 'Meeting')], default='POMODORO', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('focus_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
