# Generated by Django 5.1.15 on 2026-09-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='focussession',
            name='distracted_secs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='focussession',
            name='productive_secs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='focussession',
            name='productivity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='focussession',
            name='switches_count',
            field=models.IntegerField(default=0),
        ),
    ]
