# Generated by Django 5.1.15 on 2026-09-09 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_process', models.CharField(blank=True, default='', max_length=255)),
                ('from_app', models.CharField(blank=True, default='', max_length=255)),
                ('from_title', models.CharField(blank=True, default='', max_length=512)),
                ('from_category', models.CharField(blank=True, default='', max_length=50)),
                ('to_process', models.CharField(blank=True, default='', max_length=255)),
                ('to_app', models.CharField(blank=True, default='', max_length=255)),
                ('to_title', models.CharField(blank=True, default='', max_length=512)),
                ('to_category', models.CharField(blank=True, default='', max_length=50)),
                ('switched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_switches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-switched_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(db_index=True, max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('window_title', models.CharField(blank=True, default='', max_length=512)),
                ('exe_path', models.CharField(blank=True, default='', max_length=1024)),
                ('category', models.CharField(choices=[('DEVELOPMENT', 'Development / Coding'), ('PRODUCTIVE', 'Productive / Work'), ('CREATIVE', 'Creative'), ('COMMUNICATION', 'Communication'), ('BROWSER', 'Web Browser'), ('ENTERTAINMENT', 'Entertainment / Media'), ('GAMING', 'Gaming'), ('SOCIAL_MEDIA', 'Social Media'), ('SYSTEM', 'System / Utility'), ('EDUCATION', 'Education / Learning'), ('FINANCE', 'Finance'), ('SHOPPING', 'Shopping')], default='SYSTEM', max_length=50)),
                ('productivity_label', models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('NEUTRAL', 'Neutral'), ('DISTRACTING', 'Distracting')], default='NEUTRAL', max_length=20)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_secs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'started_at'], name='system_moni_user_id_273956_idx')],
            },
        ),
    ]
