# Generated by Django 5.1.15 on 2026-09-10 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_sessions', '0002_focussession_distracted_secs_and_more'),
        ('system_monitor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('FOCUSED', 'Focused on Screen'), ('LOOKING_AT_PHONE', 'Distracted (Looking Down / Phone)'), ('LOOKING_AWAY', 'Distracted (Looking Away)'), ('USER_ABSENT', 'User Absent / Away from Desk'), ('DROWSY', 'Drowsy / Fatigue Detected')], db_index=True, default='FOCUSED', max_length=30)),
                ('pitch', models.FloatField(default=0.0)),
                ('yaw', models.FloatField(default=0.0)),
                ('roll', models.FloatField(default=0.0)),
                ('attention_score', models.FloatField(default=100.0)),
                ('duration_secs', models.IntegerField(default=3)),
                ('face_detected', models.BooleanField(default=True)),
                ('emotion', models.CharField(blank=True, default='', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attention_logs', to='focus_sessions.focussession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attention_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='system_moni_user_id_f28941_idx')],
            },
        ),
    ]
