# Generated by Django 5.1.15 on 2026-09-09 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1024)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('page_title', models.CharField(blank=True, default='', max_length=512)),
                ('visited_at', models.DateTimeField()),
                ('time_spent_secs', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('DEVELOPMENT', 'Development'), ('EDUCATION', 'Education'), ('CREATIVE', 'Creative'), ('COMMUNICATION', 'Communication'), ('FINANCE', 'Finance'), ('SYSTEM', 'System'), ('NEWS_READING', 'News & Reading'), ('ENTERTAINMENT', 'Entertainment'), ('SOCIAL_MEDIA', 'Social Media'), ('GAMING', 'Gaming'), ('SHOPPING', 'Shopping')], default='SYSTEM', max_length=50)),
                ('productivity_label', models.CharField(choices=[('PRODUCTIVE', 'Productive'), ('NEUTRAL', 'Neutral'), ('DISTRACTING', 'Distracting')], default='NEUTRAL', max_length=20)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BrowsingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255)),
                ('session_start', models.DateTimeField()),
                ('session_end', models.DateTimeField()),
                ('total_time_secs', models.IntegerField(default=0)),
                ('productivity_label', models.CharField(default='NEUTRAL', max_length=20)),
                ('page_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
