# Generated by Django 5.1.15 on 2026-09-09 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browsing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_domain', models.CharField(blank=True, default='', max_length=255)),
                ('from_title', models.CharField(blank=True, default='', max_length=512)),
                ('from_category', models.CharField(blank=True, default='', max_length=50)),
                ('to_domain', models.CharField(blank=True, default='', max_length=255)),
                ('to_title', models.CharField(blank=True, default='', max_length=512)),
                ('to_category', models.CharField(blank=True, default='', max_length=50)),
                ('switched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switch_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-switched_at'],
            },
        ),
    ]
