# Generated by Django 5.1.15 on 2026-09-09 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=255, unique=True)),
                ('item_type', models.CharField(default='app', max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('productivity_label', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('date_analyzed', models.DateField()),
                ('focus_score', models.FloatField(default=0.0)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('distraction_score', models.FloatField(default=0.0)),
                ('top_distractors', models.JSONField(blank=True, default=list)),
                ('insights_text', models.TextField()),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('retrieved_chunks', models.JSONField(blank=True, default=list)),
                ('llm_model_used', models.CharField(default='mistralai/Mistral-7B-Instruct-v0.2', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
